In [4]:
import gensim.downloader as api

wv = api.load("word2vec-google-news-300")

[==================================================] 100.0% 1662.8/1662.8MB downloaded


In [2]:
pip install gensim

Note: you may need to restart the kernel to use updated packages.


In [49]:
dir(wv)

['__class__',
 '__contains__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__len__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__setitem__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 '_adapt_by_suffix',
 '_load_specials',
 '_log_evaluate_word_analogies',
 '_save_specials',
 '_smart_save',
 '_upconvert_old_d2vkv',
 '_upconvert_old_vocab',
 'add_lifecycle_event',
 'add_vector',
 'add_vectors',
 'allocate_vecattrs',
 'closer_than',
 'cosine_similarities',
 'distance',
 'distances',
 'doesnt_match',
 'evaluate_word_analogies',
 'evaluate_word_pairs',
 'expandos',
 'fill_norms',
 'get_index',
 'get_mean_vector',
 'get_normed_vectors',
 'get_vecattr',
 'get_vector',
 'has_index_for',
 'index2entity',
 'index2word',
 'index_to_key',
 'init_sims',
 

In [50]:
wv.similarity(w1='great',w2='good')

0.72915095

In [51]:
wv.similarity(w1='great',w2='better')

0.43074462

In [52]:
wv.similarity(w1='great',w2='well')

0.4098271

In [53]:
# These similarities are based upon the context in whoch these words appeared in the training documents. This similarity has nothing to do with "Synonym" of english language

In [54]:
wv.similarity(w1='profit',w2='gain')

0.28772825

In [55]:
wv.similarity(w1='profit',w2='loss')

0.34199455

In [56]:
wv.similarity(w1='profit',w2='revenue')

0.5829346

In [57]:
wv.most_similar("good")

[('great', 0.7291510105133057),
 ('bad', 0.7190051078796387),
 ('terrific', 0.6889115571975708),
 ('decent', 0.6837348341941833),
 ('nice', 0.6836092472076416),
 ('excellent', 0.644292950630188),
 ('fantastic', 0.6407778263092041),
 ('better', 0.6120728850364685),
 ('solid', 0.5806034803390503),
 ('lousy', 0.576420247554779)]

article1 ="I was feeling good as it was holiday"

article2="I was feeling bad as it was holiday"

Here if we see the context in which 'good' and 'bad' are used in these 2 sentences is same...the neighbouring words for good/bad are almost same ...So based upon this, the two words are said to be similar in NLP

In [58]:
wv.most_similar("dog")

[('dogs', 0.8680489659309387),
 ('puppy', 0.8106428384780884),
 ('pit_bull', 0.780396044254303),
 ('pooch', 0.7627376914024353),
 ('cat', 0.7609457969665527),
 ('golden_retriever', 0.7500901818275452),
 ('German_shepherd', 0.7465174198150635),
 ('Rottweiler', 0.7437615394592285),
 ('beagle', 0.7418621778488159),
 ('pup', 0.740691065788269)]

In [59]:
wv.most_similar("cat")

[('cats', 0.8099379539489746),
 ('dog', 0.760945737361908),
 ('kitten', 0.7464985251426697),
 ('feline', 0.7326234579086304),
 ('beagle', 0.7150582671165466),
 ('puppy', 0.7075453400611877),
 ('pup', 0.6934291124343872),
 ('pet', 0.6891531348228455),
 ('felines', 0.6755931973457336),
 ('chihuahua', 0.6709762215614319)]

 dog and cats mostly occurs in similar context in most of the articles

King - man + woman = Queen

France -Paris + Berlin = Germany

In [24]:
wv.most_similar(positive=["king", "woman"],negative=["man"])

[('queen', 0.7118193507194519),
 ('monarch', 0.6189674139022827),
 ('princess', 0.5902431011199951),
 ('crown_prince', 0.5499460697174072),
 ('prince', 0.5377321839332581),
 ('kings', 0.5236844420433044),
 ('Queen_Consort', 0.5235945582389832),
 ('queens', 0.5181134343147278),
 ('sultan', 0.5098593831062317),
 ('monarchy', 0.5087411999702454)]

In [60]:
wv.most_similar(positive=["France", "Berlin"],negative=["Paris"])

[('Germany', 0.7901254892349243),
 ('Austria', 0.6026812195777893),
 ('German', 0.6004959940910339),
 ('Germans', 0.5851002931594849),
 ('Poland', 0.5847075581550598),
 ('Hungary', 0.5271855592727661),
 ('BBC_Tristana_Moore', 0.5249711275100708),
 ('symbol_RSTI', 0.5245768427848816),
 ('Belgium', 0.5221248269081116),
 ('Germnay', 0.5199405550956726)]

In [61]:
wv.most_similar(positive=["France", "Ranchi"],negative=["Paris"])

[('Jharkhand', 0.6881963610649109),
 ('Karnataka', 0.6507984399795532),
 ('Jamshedpur', 0.6432908177375793),
 ('Andhra_Pradesh', 0.6432713270187378),
 ('Uttar_Pradesh', 0.639927327632904),
 ('Madhya_Pradesh', 0.6392531991004944),
 ('Chhattisgarh', 0.6388451457023621),
 ('Bihar', 0.6377339959144592),
 ('Orissa', 0.6325611472129822),
 ('Maharashtra', 0.6291553974151611)]

In [62]:
wv.doesnt_match(['Apple','Cat','Google','tata Steel'])

'Cat'

In [63]:
wv.doesnt_match(['Dog','Cat','Lion','Sparrow'])

'Sparrow'

In [64]:
glv  = api.load('glove-twitter-25')

In [41]:
# below results are given based upon training data from twitter so it may differ from waht we got from google news model

In [65]:
glv.most_similar("good")

[('too', 0.9648017287254333),
 ('day', 0.9533665180206299),
 ('well', 0.9503170847892761),
 ('nice', 0.9438973665237427),
 ('better', 0.9425962567329407),
 ('fun', 0.9418926239013672),
 ('much', 0.9413353800773621),
 ('this', 0.9387555122375488),
 ('hope', 0.9383506774902344),
 ('great', 0.9378516674041748)]

In [67]:
glv.doesnt_match("banana grapes oranges human".split(' '))

'human'

In [70]:
wv_great=wv['great']
wv_good=wv['good']

In [71]:
wv_great.shape

(300,)

In [72]:
wv_great

array([ 7.17773438e-02,  2.08007812e-01, -2.84423828e-02,  1.78710938e-01,
        1.32812500e-01, -9.96093750e-02,  9.61914062e-02, -1.16699219e-01,
       -8.54492188e-03,  1.48437500e-01, -3.34472656e-02, -1.85546875e-01,
        4.10156250e-02, -8.98437500e-02,  2.17285156e-02,  6.93359375e-02,
        1.80664062e-01,  2.22656250e-01, -1.00585938e-01, -6.93359375e-02,
        1.04427338e-04,  1.60156250e-01,  4.07714844e-02,  7.37304688e-02,
        1.53320312e-01,  6.78710938e-02, -1.03027344e-01,  4.17480469e-02,
        4.27246094e-02, -1.10351562e-01, -6.68945312e-02,  4.19921875e-02,
        2.50000000e-01,  2.12890625e-01,  1.59179688e-01,  1.44653320e-02,
       -4.88281250e-02,  1.39770508e-02,  3.55529785e-03,  2.09960938e-01,
        1.52343750e-01, -7.32421875e-02,  2.16796875e-01, -5.76171875e-02,
       -2.84423828e-02, -3.60107422e-03,  1.52343750e-01, -2.63671875e-02,
        2.13623047e-02, -1.51367188e-01,  1.04003906e-01,  3.18359375e-01,
       -1.85546875e-01,  

In [73]:
import pandas as pd

df =pd.read_csv('fake_and_real_news.csv')

df.head()

Text label
0   Top Trump Surrogate BRUTALLY Stabs Him In The...  Fake
1  U.S. conservative leader optimistic of common ...  Real
2  Trump proposes U.S. tax overhaul, stirs concer...  Real
3   Court Forces Ohio To Allow Millions Of Illega...  Fake
4  Democrats say Trump agrees to work on immigrat...  Real

In [74]:
df.shape

(9900, 2)

In [76]:
df.label.value_counts()

Fake    5000
Real    4900
Name: label, dtype: int64

In [78]:
df['label_num'] = df.label.map({
                                'Fake':0,
                                'Real':1
                               })

In [79]:
df

Text label  label_num
0      Top Trump Surrogate BRUTALLY Stabs Him In The...  Fake          0
1     U.S. conservative leader optimistic of common ...  Real          1
2     Trump proposes U.S. tax overhaul, stirs concer...  Real          1
3      Court Forces Ohio To Allow Millions Of Illega...  Fake          0
4     Democrats say Trump agrees to work on immigrat...  Real          1
...                                                 ...   ...        ...
9895   Wikileaks Admits To Screwing Up IMMENSELY Wit...  Fake          0
9896  Trump consults Republican senators on Fed chie...  Real          1
9897  Trump lawyers say judge lacks jurisdiction for...  Real          1
9898   WATCH: Right-Wing Pastor Falsely Credits Trum...  Fake          0
9899   Sean Spicer HILARIOUSLY Branded As Chickensh*...  Fake          0

[9900 rows x 3 columns]

In [97]:
import spacy
nlp = spacy.load('en_core_web_lg')

def preprocess_and_vectorize(text):
    filtered_words=[]
    doc = nlp(text)
    for token in doc:
        if token.is_stop or token.is_punct:
            continue
        filtered_words.append(token.lemma_)
    return wv.get_mean_vector(filtered_words) # this will give the sentence vector embedding
        
    

In [98]:
preprocess_and_vectorize("Don't worry if you don't understand")

array([ 0.00235079, -0.00284596, -0.03638233,  0.00413919, -0.10635224,
        0.05758579,  0.13348952, -0.00689176,  0.05995331, -0.02875906,
       -0.02279907, -0.06939262, -0.01549996,  0.03538099, -0.0873947 ,
        0.10044542,  0.02490648,  0.11501945,  0.00442711, -0.07228819,
       -0.04447255,  0.02785169,  0.03338735,  0.02222995,  0.07053161,
        0.06723307,  0.03483712, -0.0873695 ,  0.04152397, -0.0969665 ,
       -0.00914938,  0.00555944, -0.0277799 , -0.00701522,  0.05281431,
       -0.01066206,  0.02466576,  0.02378148,  0.0279402 ,  0.05527755,
        0.01359304, -0.01062085,  0.06734448, -0.03492254, -0.08421434,
       -0.04324378, -0.03578918, -0.00817786, -0.02093195,  0.01856531,
       -0.07064191,  0.05023994, -0.03036207, -0.0412168 , -0.00684169,
        0.05189689, -0.04097777, -0.05789134,  0.044417  , -0.0470418 ,
       -0.01475445,  0.01373999, -0.00459672,  0.00419459,  0.04307397,
       -0.01500929, -0.08037488,  0.05358911, -0.0211829 , -0.00

In [87]:
v1=wv['worry']
v2=wv['understand']

In [90]:
import numpy as np

np.mean([v1,v2],axis=0)[:3]

array([ 0.00976562, -0.00561523, -0.08905029], dtype=float32)

In [94]:
wv.get_mean_vector(['worry','understand'],pre_normalize=False)[:3]

array([ 0.00976562, -0.00561523, -0.08905029], dtype=float32)

In [ ]:
df['vector'] = df.Text.apply(preprocess_and_vectorize)

In [ ]:
df.head()